### ISSUE TITLE
SSH name resolution fails in latest image version

### ISSUE THREAD

**Issue by fenech** [troykinsella/concourse-ansible-playbook-resource#19]
It looks like the behaviour of SSH has changed in the latest image `28239a6eb5b4`. It defaults to using IPv6, which causes lookups which were previously working to fail.

A workaround for this issue is to add the following to the source configuration of the resource:
```
source:
  ssh_common_args: "-4"
```

**Comment by serverwentdown** [comment]
Could it be because your network is configured with IPv6, but unable to route? 

Anyway, this doesn't seem like a bug with this resource.

**Comment by fenech** [comment]
I agree, not a bug here, just a change in behaviour :+1:

**Comment by troykinsella** [comment]
Thanks for calling out the solution! Closing.
