### ISSUE TITLE
New build/release for current ansible version

### ISSUE THREAD

**Issue by mherold** [troykinsella/concourse-ansible-playbook-resource#24]
@troykinsella Just wondering whether you could re-build and release a new version (since it's been > 1 year) so we have a more recent version of ansible? Thanks! ;-)

**Comment by troykinsella** [comment]
Thanks for the reminder! I'll take a look today.
In the meantime, are you aware of anything about the current role and publication that limit use of a newer Ansible version?
Thank you!

**Comment by mherold** [comment]
Thanks!
No, I'm not aware of anything that would limit the use of a newer ansible version - although I can't say I'm exactly sure how  much that means ;-) Anything specific I can help with having a look at?

**Comment by troykinsella** [comment]
Pushed tag `2.2.2`, and `latest` with a fresh build!
