### ISSUE TITLE
New build/release for current ansible version

### ISSUE THREAD

**Issue by mherold** [troykinsella/concourse-ansible-playbook-resource#26]
@troykinsella  Hello again ;-) Just wondering whether you could re-build and release a new version so we have the option of using the current ansible version (7.x / ansible-core 2.14)?

Haven't explicitly checked whether the new version could introduce problems, but I'm not aware of any. https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_7.html

Thanks a lot!

**Comment by mherold** [comment]
@troykinsella ping? meanwhile it's 8.x / ansible-core 2.15 ;-)

Thanks!

**Comment by troykinsella** [comment]
Pushed a fresh build to the `latest` tag. Thanks for your patience!

```
d91ec583a481:/# ansible --version
ansible [core 2.15.1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.4 (main, Jun  9 2023, 02:29:05) [GCC 12.2.1 20220924] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = False
```
