### ISSUE TITLE
Ruby version compatibility issues in `latest` tagged image

### ISSUE THREAD

**Issue by waweber** [troykinsella/concourse-ansible-playbook-resource#27]
```
/opt/resource/lib/commands/out.rb:82:in `configure_ansible!': undefined method `exists?' for File:Class (NoMethodError)


      if File.exists? ansible_cfg_path

             ^^^^^^^^

Did you mean?  exist?

	from /opt/resource/lib/commands/out.rb:195:in `run!'

	from /opt/resource/lib/commands/out.rb:208:in `<main>'
```

According to [this StackOverflow answer](https://stackoverflow.com/a/75353113) it looks like Ruby 3.2.0 removes some deprecated aliases that need to be updated in this resource (or have a specific Ruby version pinned)

**Comment by troykinsella** [comment]
@waweber Thanks for the report, and thanks for your patience!
Seems my rspec test strategy no longer works (i.e. doesn't run at all) with buildkit.
